image: jekyll/jekyll

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - gem install kramdown -v '2.4.0' --source 'https://rubygems.org/'
  - gem install rb-fsevent -v '0.11.2' --source 'https://rubygems.org/'
  - gem install bundler
  - bundle install

test:
  stage: test
  script:
    - bundle exec jekyll build -d test
  artifacts:
    paths:
      - test
  except:
    - main

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - main
