# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Beginning of MidAtlantic Dreamin' Jekyll site using GitLab Pages
email:  midatlanticdreamin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  MidAtlantic Dreamin', formerly known as the Phillyforce conference, is the
  Salesforce community conference for folks from New York to DC. Mark your 
  calendar now for May 6, 2020!
baseurl: "/mad-website" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site
twitter_username: phillyforce
#github_username:  jekyll
gitlab_username:  madreamin

# Outputting
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: kramdown
exclude: ["README.md"]